### ISSUE TITLE
Week 2 notes link broken 

### ISSUE THREAD

**Issue by paulagardner** [ThorntonLab/AdvancedInformatics2021#8]
in README: all links under Week2 headers broken: https://github.com/ThorntonLab/AdvancedInformatics2021/blob/main/week2notes 
https://github.com/ThorntonLab/AdvancedInformatics2021/blob/main/NotebookSlides
https://github.com/ThorntonLab/AdvancedInformatics2021/blob/main/week2lab

**Comment by molpopgen** [comment]
I cannot replicate this from the [class site](http://www.molpopgen.org/AdvancedInformatics2021/).  Clicking on those links works on both firefox and chrome.  What browser are you using that is failing?

**Comment by paulagardner** [comment]
Chrome.

**Comment by molpopgen** [comment]
And you are going from the website, and not the README as displayed on github?  The links should not work from there.

**Comment by molpopgen** [comment]
This the what I get from chrome.  Note that I'm at the website, not the repo.

![Peek 2021-01-15 11-34](https://user-images.githubusercontent.com/6416159/104770762-f0c85780-5725-11eb-99cd-f64060a309d4.gif)

**Comment by paulagardner** [comment]
Yep, was going through the repo. Thanks for clearing that up.
